version: 2

sources:
  - name: raw
    database: client_data
    schema: dbo
    tables:
      - name: productos
      - name: depositos
      - name: presupuesto_por_cliente
      - name: productos_por_deposito
      - name: clientes
      - name: backorder
      - name: ventas
      - name: motivos_de_devolucion
      - name: vendedores
      - name: grupos
      - name: distritos
      - name: corregimientos
      - name: provincias
      - name: tipos
      - name: clases
      - name: estado_de_cuenta_de_clientes
