version: 2

sources:
  - name: raw
    database: "AINOMICS"
    schema: dbo
    tables:
      - name: ventas
      - name: backorder
      - name: depositos
      - name: productos
      - name: productos_por_deposito
      - name: clientes
      - name: motivo_de_devolucion
      - name: export_all